// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTc6KslPKkmjyes74AKZNWSBEYFrQ-uM',
    appId: '1:908406818469:android:bf87f305594a0dd871af4c',
    messagingSenderId: '908406818469',
    projectId: 'flutternew-c90e6',
    storageBucket: 'flutternew-c90e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59gSId7v-A1gV0UM7ApUEqiwsHZZlJIs',
    appId: '1:908406818469:ios:c1368f85d3b8f28c71af4c',
    messagingSenderId: '908406818469',
    projectId: 'flutternew-c90e6',
    storageBucket: 'flutternew-c90e6.appspot.com',
    iosBundleId: 'com.example.clients',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxEda1JYYn9tl5n_xl9vN53NREaqsBwoA',
    appId: '1:908406818469:web:b781ce9dd0660cab71af4c',
    messagingSenderId: '908406818469',
    projectId: 'flutternew-c90e6',
    authDomain: 'flutternew-c90e6.firebaseapp.com',
    storageBucket: 'flutternew-c90e6.appspot.com',
    measurementId: 'G-365M0WN5Z9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59gSId7v-A1gV0UM7ApUEqiwsHZZlJIs',
    appId: '1:908406818469:ios:ccafea0b6dd0273471af4c',
    messagingSenderId: '908406818469',
    projectId: 'flutternew-c90e6',
    storageBucket: 'flutternew-c90e6.appspot.com',
    iosBundleId: 'com.example.bustracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxEda1JYYn9tl5n_xl9vN53NREaqsBwoA',
    appId: '1:908406818469:web:788ec4875308085d71af4c',
    messagingSenderId: '908406818469',
    projectId: 'flutternew-c90e6',
    authDomain: 'flutternew-c90e6.firebaseapp.com',
    storageBucket: 'flutternew-c90e6.appspot.com',
    measurementId: 'G-Y6YB998VRY',
  );

}